### ISSUE TITLE
cannot pass `[OPTIONS]` to codspeed build

### ISSUE THREAD

**Issue by jvdd** [CodSpeedHQ/codspeed-rust#1]
I am looking to integrate CodSpeed into my CI-CD https://github.com/jvdd/argminmax/pull/15

However, I do not manage to add the `--features half` flag to the `codspeed build` command - which is necessary to compile the benches for the optional features (which is in my case f16 support).

![image](https://user-images.githubusercontent.com/18898740/216143170-cc863936-364e-45da-a840-8dd9a7b8a656.png)

*(It might ofcourse be me doing something wrong)*

P.S.: kudos for this great project! cannot wait to have benchmarks in my CI/CD flow :)

**Comment by art049** [comment]
Thank you! 
Totally, the feature flag option is missing. I'll add support for this asap!

**Comment by art049** [comment]
Just released it in `cargo-codspeed` 1.1.0 🤓

**Comment by jvdd** [comment]
Awesome! I''ll try it out :rocket:

**Comment by jvdd** [comment]
Works like a charm! :+1:
