### ISSUE TITLE
`cargo codspeed build` not support multiple `--package` flags

### ISSUE THREAD

**Issue by EYHN** [CodSpeedHQ/codspeed-rust#19]
example

```
cargo codspeed build -p crate1 -p crate2 
```

which is supported by cargo build

**Comment by art049** [comment]
As discussed on Discord, for now a possible workaround is to run the build command multiple times:
```
cargo codspeed build -p crate1
cargo codspeed build -p crate2
```

We'll implement the behavior soon though!
