### ISSUE TITLE
`cargo binstall` not finding prebuilt `cargo-codspeed`

### ISSUE THREAD

**Issue by davidhewitt** [CodSpeedHQ/codspeed-rust#27]
See https://github.com/PyO3/pyo3/actions/runs/6587347935/job/18801342354

The `cargo-codspeed` install is building from source.

It looks like the download URL is wrong:

>  WARN resolve: Error while checking fetcher invalid url: could not HEAD https://github.com/CodSpeedHQ/codspeed-rust/tree/main/crates/cargo-codspeed/releases/download/2.3.2/cargo-codspeed.tzst: error sending request for url (https://github.com/CodSpeedHQ/codspeed-rust/tree/main/crates/cargo-codspeed/releases/download/2.3.2/cargo-codspeed.tzst): connection error: connection reset

**Comment by art049** [comment]
It now works on x86:
```
DEBUG resolve: extracted_files = ExtractedFiles(
    {
        "bin-cargo-codspeed-x86_64-unknown-linux-gnu-GhCrateMeta": File,
        ".": Dir(
            {
                "bin-cargo-codspeed-x86_64-unknown-linux-gnu-GhCrateMeta",
            },
        ),
    },
)
DEBUG Found a binary install source: github.com (x86_64-unknown-linux-gnu)
```
