### ISSUE TITLE
Update `cargo` to latest for `cargo-codspeed`?

### ISSUE THREAD

**Issue by Boshen** [CodSpeedHQ/codspeed-rust#29]
https://github.com/CodSpeedHQ/codspeed-rust/blob/dc6b1f187538d50b5cc38266833df83d00aa0ad4/crates/cargo-codspeed/Cargo.toml#L21

The newest version is 0.75.0, the current version is one year old :-(

**Comment by Boshen** [comment]
We now getting more errors due to using newer features of cargo :-(

```
 failed to parse manifest at `/home/runner/work/rolldown/rolldown/Cargo.toml`
```

https://github.com/rolldown/rolldown/actions/runs/8756227125/job/24032187182?pr=918

**Comment by adriencaccia** [comment]
@Boshen we fixed the issue, and it was released in the last version of `cargo codspeed`
I tested it out in https://github.com/adriencaccia/rolldown/pull/1, and it works again.
If that is okay with you, I can open the PR against rolldown directly.

**Comment by Boshen** [comment]
> @Boshen we fixed the issue, and it was released in the last version of `cargo codspeed` I tested it out at [adriencaccia/rolldown#1](https://github.com/adriencaccia/rolldown/pull/1), and it works again. If that is okay with you, I can open the PR against rolldown directly.

That would be nice! We can have it run side by side with the current benchmark suite and to observe its charactistics.

**Comment by adriencaccia** [comment]
Great, openend https://github.com/rolldown/rolldown/pull/1013!
