### ISSUE TITLE
The CLI benches aren't documented

### ISSUE THREAD

**Issue by ematipico** [CodSpeedHQ/codspeed-rust#32]
This **isn't** the place to open the issue, but the documentation isn't open source and I don't know where to point this out.

The CLI `cargo-codspeed` accepts some benches as shown here:

https://github.com/CodSpeedHQ/codspeed-rust/blob/fc751390d7d1a534296d899b4ec3cc8b45913c9a/crates/cargo-codspeed/src/app.rs#L24-L35

Although the documentation doesn't say anything about it, and I had to check to source code to allow to build and run specific benchmarks for specific actions.

It would be great if there was a paragraph that explains this use case, with an example where **multiple** benches are created, even dummy ones.

**Comment by adriencaccia** [comment]
@ematipico thanks for the issue!
I just added sections in the documentation about it, should be deployed soon
