### ISSUE TITLE
CLI panics when running benchmarks

### ISSUE THREAD

**Issue by marc2332** [CodSpeedHQ/codspeed-rust#35]
Hey! I am trying to set up codspeed for my project, but I am getting this error.

![image](https://github.com/CodSpeedHQ/codspeed-rust/assets/38158676/cc9b4127-01b6-48db-b7b4-a9b59bb911e1)

**Comment by marc2332** [comment]
Perhaps it is something to do with Windows

**Comment by adriencaccia** [comment]
Hey yes it seems that there is a problem with the parsing of a path when running under Windows.
I will go and make a fix. Thanks for the issue

**Comment by marc2332** [comment]
> Hey yes it seems that there is a problem with the parsing of a path when running under Windows. I will go and make a fix. Thanks for the issue

Looks like I already found a solution in https://github.com/CodSpeedHQ/codspeed-rust/pull/36 !
