### ISSUE TITLE
Allow selecting different profiles

### ISSUE THREAD

**Issue by Dekker1** [CodSpeedHQ/codspeed-rust#48]
Currently the `cargo codspeed build` command requests the `release` profile: [https://github.com/CodSpeedHQ/codspeed-rust/blob/ac3dae836b115cb972ce3d5f31cb7e55cb69cdd7/crates/cargo-codspeed/src/build.rs#L36](https://github.com/CodSpeedHQ/codspeed-rust/blob/ac3dae836b115cb972ce3d5f31cb7e55cb69cdd7/crates/cargo-codspeed/src/build.rs#L36). However, there is a standard [`bench` profile](https://doc.rust-lang.org/cargo/reference/profiles.html) that is used by `cargo bench`. Note that this `bench` by default is the same as the `release` profile, but can be overwritten by users to enable different build options for benchmarking.

I was hoping to use this profile as I would like to set `debug = true` to receive better traces in CodSpeed, but would not like to do this for the `release` profile. At the moment there doesn't seem to be a way to override the build profile that is used by the `cargo codspeed build` command.

**Comment by art049** [comment]
> I was hoping to use this profile as I would like to set debug = true to receive better traces in CodSpeed, but would not like to do this for the release profile. At the moment there doesn't seem to be a way to override the build profile that is used by the cargo codspeed build command.

You shouldn't need to add the debug configuration to your release profile manually since we pass it to rustc. So normally you should have the debug symbols already in your codspeed builds.
https://github.com/CodSpeedHQ/codspeed-rust/blob/f91abc79aa86e1def9084fcee78236bcb5eee96c/crates/cargo-codspeed/src/app.rs#L59

**Comment by Dekker1** [comment]
Thank you for the quick work! After making the issue, I did indeed find that it was my stripping settings, and not the `debug = true` settings that were the problem. Either way the new changes will resolve the problem 😄
